import {state,subscribe} from './state.js';import {loadState,saveState} from './storage.js';import {registerRoute,navigate,initRouter,getCurrentRoute} from './router.js';import {renderHome} from './pages/home.js';import {renderGames} from './pages/games.js';import {renderBypass} from './pages/bypass.js';import {renderInjection} from './pages/injection.js';import {renderSave} from './pages/save.js';import {renderFix} from './pages/fix.js';import {renderSteam} from './pages/steam.js';import {renderLogs} from './pages/logs.js';import {renderSettings} from './pages/settings.js';import {renderAbout} from './pages/about.js';
loadState();
const pages={home:renderHome,games:renderGames,bypass:renderBypass,injection:renderInjection,save:renderSave,fix:renderFix,steam:renderSteam,logs:renderLogs,settings:renderSettings,about:renderAbout};
Object.entries(pages).forEach(([name,renderer])=>registerRoute(name,renderer));
const sidebarItems=[['Overview','home','Home','layout-dashboard'],['Overview','games','Games','gamepad-2'],['Tools','bypass','Bypass','shield-check'],['Tools','injection','Injection','syringe'],['Tools','save','Save & Restore','archive'],['Tools','fix','Fix','wrench'],['Tools','steam','Steam','database'],['System','logs','Activity Logs','scroll-text'],['System','settings','Settings','settings-2'],['System','about','About','info']];
function drawChrome(){const sb=document.querySelector('#sidebar');const collapsed=state.ui.sidebarCollapsed;sb.className=`sidebar ${collapsed?'collapsed':''}`;sb.innerHTML=`<div class="brand"><div class="brand-mark">SGT</div><div class="brand-copy"><strong>Steam Game Tools</strong><span>Prototype</span></div></div><nav>${sidebarItems.map(([group,path,label,icon],i)=>`${i===0||sidebarItems[i-1][0]!==group?`<div class="nav-label">${group}</div>`:''}<button class="nav-item" data-path="${path}" title="${label}"><i data-lucide="${icon}"></i><span>${label}</span></button>`).join('')}</nav><div class="sidebar-footer"><button id="collapse" class="nav-item" title="Collapse Sidebar"><i data-lucide="panel-left-close"></i><span>Collapse Sidebar</span></button><div class="mock-status"><span></span><div><strong>Mock Mode</strong><small>Browser only</small></div></div></div>`;sb.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>navigate(b.dataset.path));sb.querySelector('#collapse').onclick=()=>{state.ui.sidebarCollapsed=!state.ui.sidebarCollapsed;saveState();drawChrome()};window.lucide?.createIcons({nodes:[sb]});}
function drawTopbar(){const top=document.querySelector('#topbar');top.innerHTML=`<div class="breadcrumbs"><span>Steam Game Tools</span><i data-lucide="chevron-right"></i><strong id="crumb">Home</strong></div><div class="top-actions"><button class="search-trigger" id="global-search"><kbd>Ctrl</kbd><kbd>K</kbd><span>Search anything...</span></button><button class="icon-btn" title="Keyboard shortcuts" id="shortcuts"><i data-lucide="keyboard"></i></button></div>`;top.querySelector('#global-search').onclick=openSearch;top.querySelector('#shortcuts').onclick=openShortcuts;window.lucide?.createIcons({nodes:[top]});}
function openSearch(){const overlay=document.createElement('div');overlay.className='search-overlay';overlay.innerHTML=`<div class="search-modal"><div class="search-input"><i data-lucide="search"></i><input autofocus placeholder="Search games, tools, settings, logs..."></div><div class="search-results"></div><p class="search-hint">Press Esc to close</p></div>`;document.body.appendChild(overlay);const input=overlay.querySelector('input'),results=overlay.querySelector('.search-results');const draw=()=>{const q=input.value.toLowerCase();const items=[...state.games.map(g=>({title:g.name,sub:'Game Library',path:'games'})),...sidebarItems.map(x=>({title:x[2],sub:'Navigation',path:x[1]}))].filter(x=>!q||x.title.toLowerCase().includes(q));results.innerHTML=items.slice(0,10).map(x=>`<button class="search-result" data-path="${x.path}"><i data-lucide="arrow-up-right"></i><div><strong>${x.title}</strong><span>${x.sub}</span></div></button>`).join('')||'<div class="empty-search">No results found.</div>';results.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>{overlay.remove();navigate(b.dataset.path)});window.lucide?.createIcons({nodes:[overlay]});};input.oninput=draw;draw();const close=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)close()};overlay._close=close;}
function openShortcuts(){const root=document.createElement('div');root.className='shortcuts-modal';root.innerHTML=`<div class="shortcut-card"><div class="modal-head"><h3>Keyboard Shortcuts</h3><button class="icon-btn" id="x"><i data-lucide="x"></i></button></div><div class="shortcut-list">${[['Ctrl + K','Global Search'],['Ctrl + 1','Home'],['Ctrl + 2','Games'],['Ctrl + 3','Bypass'],['Ctrl + 4','Injection'],['Ctrl + 5','Save & Restore'],['Ctrl + 6','Fix'],['Ctrl + ,','Settings'],['Esc','Close Modal / Search']].map(x=>`<div><span>${x[1]}</span><kbd>${x[0]}</kbd></div>`).join('')}</div></div>`;document.body.appendChild(root);root.querySelector('#x').onclick=()=>root.remove();root.onclick=e=>{if(e.target===root)root.remove()};window.lucide?.createIcons({nodes:[root]});}
function render(path=getCurrentRoute()){const renderer=pages[path]||pages.home;const result=renderer();const content=document.querySelector('#page-content');content.innerHTML='';if(result?.element){content.appendChild(result.element);}else if(result?.html){content.innerHTML=result.html;result.bind?.(content);}else content.innerHTML='<div class="empty-state"><h3>Page unavailable</h3></div>';document.querySelector('#crumb').textContent=(sidebarItems.find(x=>x[1]===path)||['','home','Home'])[2];drawChrome();drawTopbar();}
window.addEventListener('routechange',e=>render(e.detail.path));
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if((e.ctrlKey||e.metaKey)&&e.key==='1'){e.preventDefault();navigate('home')}if((e.ctrlKey||e.metaKey)&&e.key==='2'){e.preventDefault();navigate('games')}if((e.ctrlKey||e.metaKey)&&e.key==='3'){e.preventDefault();navigate('bypass')}if((e.ctrlKey||e.metaKey)&&e.key==='4'){e.preventDefault();navigate('injection')}if((e.ctrlKey||e.metaKey)&&e.key==='5'){e.preventDefault();navigate('save')}if((e.ctrlKey||e.metaKey)&&e.key==='6'){e.preventDefault();navigate('fix')}if((e.ctrlKey||e.metaKey)&&e.key===','){e.preventDefault();navigate('settings')}if(e.key==='Escape'){document.querySelector('.search-overlay')?.remove();document.querySelector('.shortcuts-modal')?.remove()}});
subscribe(()=>saveState());initRouter();render();
