const games=[
{name:"Cyberpunk 2077",id:"1091500",status:"Installed",favorite:true},
{name:"Batman: Arkham City",id:"200260",status:"Installed",favorite:false},
{name:"Assassin's Creed Origins",id:"582160",status:"Needs Fix",favorite:false},
{name:"Grand Theft Auto V",id:"271590",status:"Installed",favorite:false},
{name:"The Witcher 3",id:"292030",status:"Backup Available",favorite:false},
{name:"Red Dead Redemption 2",id:"1174180",status:"Installed",favorite:false},
{name:"Marvel's Spider-Man Remastered",id:"1817070",status:"Installed",favorite:false}
];
let logs=JSON.parse(localStorage.getItem("sgt_logs")||"[]");
let settings=JSON.parse(localStorage.getItem("sgt_settings")||'{"confirm":true,"animation":true}');
let backups=JSON.parse(localStorage.getItem("sgt_backups")||"[]");
const content=document.querySelector("#content"), title=document.querySelector("#page-title");
const pages={home:home,games:gamesPage,bypass:bypass,injection:injection,save:save,fix:fix,steam:steam,logs:logsPage,settings:settingsPage,about:about};
function save(){localStorage.setItem("sgt_logs",JSON.stringify(logs));localStorage.setItem("sgt_settings",JSON.stringify(settings));localStorage.setItem("sgt_backups",JSON.stringify(backups))}
function toast(msg){const t=document.querySelector("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2300)}
function log(game,action,result="SUCCESS"){logs.unshift({time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),game,action,result});save()}
function modal(titleText,body,run){const root=document.querySelector("#modal-root");root.innerHTML=`<div class="modal-backdrop"><div class="modal"><h3>${titleText}</h3><p>${body}</p><div class="modal-actions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="continue">Continue</button></div></div></div>`;root.querySelector("#cancel").onclick=()=>root.innerHTML="";root.querySelector("#continue").onclick=()=>{root.innerHTML="";run()}}
function simulate(name,steps,cb){const root=document.querySelector("#modal-root");root.innerHTML=`<div class="modal-backdrop"><div class="modal"><h3>${name}</h3><p id="step">${steps[0]}</p><div class="progress"><i></i></div></div></div>`;let i=0;const p=root.querySelector(".progress i"),s=root.querySelector("#step"),timer=setInterval(()=>{i++;p.style.width=Math.min(100,i/steps.length*100)+"%";s.textContent=steps[i]||"Completed";if(i>=steps.length){clearInterval(timer);setTimeout(()=>{root.innerHTML="";cb()},350)}},500)}
function run(action,game){const go=()=>simulate(action,["Preparing...","Checking files...","Checking dependencies...","Applying simulated configuration...","Completed"],()=>{log(game,action);toast(`${action} completed`);render(current)});settings.confirm?modal("Confirm action",`Run ${action.toLowerCase()} for ${game}? This prototype uses simulation only.`,go):go()}
function home(){return `<div class="hero"><div><span class="eyebrow">OVERVIEW</span><h2>Good evening</h2><div class="sub">Manage your Steam games and tools from one place.</div></div></div><div class="grid stats">${stat("History Inject",logs.filter(x=>x.action.includes("Injection")).length)}${stat("History Bypass",logs.filter(x=>x.action.includes("Bypass")).length)}${stat("Total Games",games.length)}${stat("Total Backups",backups.length)}</div><br><div class="grid two"><div class="card"><h3 class="section-title">Recent Activity</h3><div class="activity">${logs.slice(0,5).map(l=>`<div class="activity-row"><div><b>${l.game}</b><br><small>${l.action}</small></div><small>${l.time}</small></div>`).join("")||'<div class="empty">No activity yet.</div>'}</div></div><div class="card"><h3 class="section-title">Quick Actions</h3><div class="actions"><button class="btn primary" onclick="scan()">Scan Steam Library</button><button class="btn" onclick="run('Backup','Cyberpunk 2077')">Create Backup</button><button class="btn" onclick="run('File Verification','Cyberpunk 2077')">Verify Game</button><button class="btn" onclick="run('Steam Restart','Steam')">Restart Steam</button></div></div></div>`}
function stat(a,v){return `<div class="card"><div class="stat-title">${a}</div><div class="stat-value stat-accent">${v}</div></div>`}
function gamesPage(){return `<div class="hero"><div><span class="eyebrow">LIBRARY</span><h2>Games</h2><div class="sub">Manage your registered Steam games.</div></div></div><div class="toolbar"><input class="input" id="gameSearch" placeholder="Search games..."><select class="select" id="filter"><option>All</option><option>Installed</option><option>Needs Fix</option><option>Backup Available</option><option>Favorites</option></select></div><div class="games-grid" id="gameGrid">${gameCards(games)}</div>`}
function gameCards(list){return list.map((g,i)=>`<div class="card game-card"><div class="cover">${g.name}</div><div class="game-body"><div class="game-name">${g.name}</div><span class="badge ${g.status==="Installed"?"success":"warn"}">${g.status}</span><div class="game-meta">Steam App ID: ${g.id}<br>Last activity: Recently</div><div class="game-actions"><button class="btn" onclick="details(${i})">Details</button><button class="btn" onclick="run('File Verification','${g.name}')">Verify</button><button class="btn" onclick="favorite(${i})">${g.favorite?"★":"☆"}</button></div></div></div>`).join("")||'<div class="empty">No games found.</div>'}
function details(i){const g=games[i];modal(g.name,`Steam App ID: ${g.id}<br>Status: ${g.status}<br><br>Prototype install path: C:\\Program Files (x86)\\Steam\\steamapps\\common\\${g.name.replaceAll(" ","_")}`,()=>run("Scan",g.name))}
function favorite(i){games[i].favorite=!games[i].favorite;toast("Favorite updated");render("games")}
function toolPage(items){return `<div class="hero"><div><span class="eyebrow">TOOLS</span><h2>${current==="injection"?"Injection Tools":current==="bypass"?"Bypass Tools":current==="fix"?"Fix Tools":"Tool"}</h2><div class="sub">Prototype workflows are simulated and do not modify Steam or game security.</div></div></div><div class="grid tool-grid">${items.map(x=>`<div class="card tool-card"><h3>${x[0]}</h3><p>${x[1]}</p><button class="btn primary" onclick="run('${x[0]}','Cyberpunk 2077')">${x[2]||"Run Tool"}</button></div>`).join("")}</div>`}
function bypass(){return toolPage([["Online Fix","Simulated online compatibility workflow."],["Game Launch Fix","Simulates launch troubleshooting."],["Compatibility Check","Checks simulated compatibility data.","Check"]])}
function injection(){return toolPage([["Injection Simulation","Simulated integration workflow only."],["Compatibility Scan","Checks simulated tool compatibility.","Scan"],["Tool Validation","Validates mock installation state.","Validate"]])}
function fix(){return toolPage([["Verify Game Files","Simulated file verification."],["Repair Configuration","Simulated configuration repair."],["Check Dependencies","Checks simulated dependencies."],["Reset Game Configuration","Simulates resetting configuration."],["Scan Missing Files","Simulates missing-file scan."],["Repair Steam Library Metadata","Simulates metadata repair."]])}
function save(){return `<div class="hero"><div><span class="eyebrow">DATA</span><h2>Save & Restore</h2><div class="sub">Protect game data with simulated local and cloud workflows.</div></div></div><div class="grid two"><div class="card"><h3 class="section-title">Local Backup</h3><p class="sub">Create a simulated backup of selected game data.</p><button class="btn primary" onclick="createBackup()">Create Backup</button><h3 class="section-title" style="margin-top:25px">Cloud Account</h3><p class="sub">Not Connected</p><button class="btn" onclick="toast('Demo cloud connection successful')">Connect Cloud</button></div><div class="card"><h3 class="section-title">Backup List</h3>${backups.map((b,i)=>`<div class="activity-row"><div><b>${b.game}</b><br><small>${b.date} · ${b.size}</small></div><button class="btn" onclick="restore(${i})">Restore</button></div>`).join("")||'<div class="empty">No backups yet.</div>'}</div></div>`}
function createBackup(){simulate("Creating Backup",["Preparing backup...","Collecting save data...","Compressing...","Verifying backup...","Completed"],()=>{backups.unshift({game:"Cyberpunk 2077",date:new Date().toLocaleDateString(),size:"1.4 GB"});log("Cyberpunk 2077","Backup Created");save();toast("Backup created successfully");render("save")})}
function restore(i){modal("Restore backup","This will replace the selected game data in the real app. Prototype only.",()=>simulate("Restoring Backup",["Checking backup...","Restoring files...","Verification...","Completed"],()=>{log(backups[i].game,"Backup Restored");toast("Backup restored");render("save")}))}
function steam(){return `<div class="hero"><div><span class="eyebrow">STEAM</span><h2>Steam</h2><div class="sub">Steam management is simulated in the browser prototype.</div></div></div><div class="grid two"><div class="card"><h3 class="section-title">Steam Status</h3><div class="stat-value" style="font-size:18px">● Running</div><p class="sub">Steam Path<br>C:\\Program Files (x86)\\Steam</p></div><div class="card"><h3 class="section-title">Steam Actions</h3><div class="actions"><button class="btn primary" onclick="run('Steam Restart','Steam')">Restart Steam</button><button class="btn" onclick="toast('Demo: opening Steam')">Open Steam</button><button class="btn" onclick="toast('Demo: opening Steam folder')">Open Steam Folder</button><button class="btn" onclick="toast('Steam status refreshed')">Refresh Status</button></div></div></div>`}
function logsPage(){return `<div class="hero"><div><span class="eyebrow">SYSTEM</span><h2>Activity Logs</h2><div class="sub">Every simulated operation is recorded locally.</div></div><button class="btn danger" onclick="clearLogs()">Clear Logs</button></div><div class="card"><div class="activity">${logs.map(l=>`<div class="activity-row"><div><b>${l.game}</b><br><small>${l.action} · <span class="${l.result==="SUCCESS"?"log-success":"log-failed"}">${l.result}</span></small></div><small>${l.time}</small></div>`).join("")||'<div class="empty">No activity yet.</div>'}</div></div>`}
function settingsPage(){return `<div class="hero"><div><span class="eyebrow">SYSTEM</span><h2>Settings</h2></div></div><div class="card"><div class="setting"><div><b>Confirm destructive actions</b><span>Ask before important simulated actions.</span></div><div class="toggle ${settings.confirm?"on":""}" onclick="toggle('confirm')"><i></i></div></div><div class="setting"><div><b>Animations</b><span>Use lightweight UI transitions.</span></div><div class="toggle ${settings.animation?"on":""}" onclick="toggle('animation')"><i></i></div></div><div class="setting"><div><b>Mock Mode</b><span>Always enabled for this browser prototype.</span></div><div class="badge success">ON</div></div><div class="setting"><div><b>Reset Demo Data</b><span>Restore initial local prototype state.</span></div><button class="btn danger" onclick="resetData()">Reset</button></div></div>`}
function about(){return `<div class="hero"><div><span class="eyebrow">STEAM GAME TOOLS</span><h2>About</h2><div class="sub">Personal Game Management & Maintenance Toolkit.</div></div></div><div class="card"><h3 class="section-title">Prototype</h3><p class="sub">HTML5 + CSS3 + Vanilla JavaScript. Browser-only mock services. No Steam, DRM, anti-cheat, credentials, or game files are modified.</p></div>`}
function scan(){simulate("Scanning Steam Library",["Locating Steam...","Reading mock library...","Checking installations...","Completed"],()=>{log("Steam","Library Scan");toast("Steam library scan completed");render("home")})}
function clearLogs(){modal("Clear activity logs","This cannot be undone in the prototype.",()=>{logs=[];save();toast("Logs cleared");render("logs")})}
function toggle(k){settings[k]=!settings[k];save();render("settings")}
function resetData(){modal("Reset demo data","Games remain available, but logs, backups and settings will be reset.",()=>{logs=[];backups=[];settings={confirm:true,animation:true};save();toast("Demo data reset");render("home")})}
let current="home";
function render(page){current=page;title.textContent=page==="save"?"Save & Restore":page==="injection"?"Injection":page[0].toUpperCase()+page.slice(1);document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));content.innerHTML=pages[page]();if(page==="games"){const search=document.querySelector("#gameSearch"),filter=document.querySelector("#filter");const update=()=>{let q=search.value.toLowerCase(),f=filter.value;let list=games.filter(g=>(g.name.toLowerCase().includes(q))&&(f==="All"||f===g.status||f==="Favorites"&&g.favorite));document.querySelector("#gameGrid").innerHTML=gameCards(list)};search.oninput=update;filter.onchange=update}}
document.querySelector("#nav").onclick=e=>{const b=e.target.closest(".nav-item");if(b)render(b.dataset.page)};
document.querySelector("#collapse").onclick=()=>document.querySelector("#sidebar").classList.toggle("collapsed");
document.querySelector("#globalSearch").onclick=()=>{const q=prompt("Search games, tools, settings, logs");if(q){const g=games.find(x=>x.name.toLowerCase().includes(q.toLowerCase()));if(g){render("games");setTimeout(()=>{document.querySelector("#gameSearch").value=q;document.querySelector("#gameSearch").dispatchEvent(new Event("input"))},0)}else toast("No matching item found")}};
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelector("#modal-root").innerHTML="";if(e.ctrlKey&&e.key.toLowerCase()==="k"){e.preventDefault();document.querySelector("#globalSearch").click()}});
render("home");
