import {state,updateState} from '../state.js';
import {gameCard} from '../components/game-card.js';
import {openModal,closeModal} from '../components/modal.js';
import {confirmAction} from '../components/confirmation.js';
import {toast} from '../components/toast.js';
import {runProgress} from '../components/progress.js';
import {simulateFix} from '../services/mockFix.js';
import {createBackup} from '../services/mockBackup.js';
export function renderGames(){
 let search='',filter='All',sort='Name';
 const root=document.createElement('div');
 root.innerHTML=`<div class="page-head"><div><span class="eyebrow">Library</span><h1>Games</h1><p>Browse, inspect and maintain your demo game library.</p></div><button class="btn btn-primary" id="scan"><i data-lucide="scan-search"></i> Scan Library</button></div><div class="toolbar"><label class="search-box"><i data-lucide="search"></i><input id="game-search" placeholder="Search games..." aria-label="Search games"></label><div id="filters" class="filter-row"></div></div><div id="game-grid" class="game-grid"></div>`;
 const draw=()=>{let games=state.games.filter(g=>g.name.toLowerCase().includes(search.toLowerCase()));if(filter==='Installed')games=games.filter(g=>g.installed);if(filter==='Ready')games=games.filter(g=>g.status==='Ready');if(filter==='Needs Fix')games=games.filter(g=>g.status==='Needs Fix');if(filter==='Backup Available')games=games.filter(g=>g.status==='Backup Available'||state.backups.some(b=>b.gameId===g.id));if(filter==='Favorites')games=games.filter(g=>g.favorite);games.sort((a,b)=>sort==='Name'?a.name.localeCompare(b.name):sort==='Recently Used'?a.lastActivity.localeCompare(b.lastActivity):a.status.localeCompare(b.status));const grid=root.querySelector('#game-grid');grid.innerHTML='';if(!games.length){grid.innerHTML=`<div class="empty-state"><i data-lucide="gamepad-2"></i><h3>No games found</h3><p>Scan your Steam library or adjust the current filters.</p><button class="btn btn-primary" id="empty-scan">Scan Library</button></div>`;}else games.forEach(g=>grid.appendChild(gameCard(g,{onOpen:game=>toast(`${game.name} open simulation started`,'info'),onDetails:showDetails})));window.lucide?.createIcons({nodes:[root]});};
 root.querySelector('#game-search').oninput=e=>{search=e.target.value;draw()};
 root.querySelector('#filters').innerHTML=['All','Installed','Ready','Needs Fix','Backup Available','Favorites'].map(x=>`<button class="filter-chip ${x==='All'?'active':''}" data-filter="${x}">${x}</button>`).join('')+`<label class="sort-field"><span>Sort</span><select id="sort"><option>Name</option><option>Recently Used</option><option>Status</option></select></label>`;
 root.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;root.querySelectorAll('.filter-chip').forEach(x=>x.classList.toggle('active',x===b));draw()});root.querySelector('#sort').onchange=e=>{sort=e.target.value;draw()};root.querySelector('#scan').onclick=()=>runProgress({title:'Scanning Steam Library',steps:['Reading demo library paths...','Discovering installed games...','Checking installation states...','Updating library index...'],onComplete:()=>toast('Library scan completed','success')});draw();return {element:root};
 function showDetails(game){openModal({title:game.name,content:`<div class="detail-hero"><div class="game-cover large" style="background:${game.cover}"><span class="cover-mark">${game.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('')}</span></div><div><span class="badge ${game.installed?'badge-success':'badge-muted'}">${game.status}</span><h3>${game.name}</h3><p>Steam App ID: ${game.appId}</p></div></div><div class="detail-grid">${detail('Install path',game.path)}${detail('Installation',game.installed?'Installed':'Not installed')}${detail('Backup status',state.backups.some(b=>b.gameId===game.id)?'Available':'No backup')}${detail('Last activity',game.lastActivity)}</div>`,actions:[{label:'Close',variant:'btn-secondary',onClick:closeModal},{label:'Create Backup',variant:'btn-primary',onClick:()=>{closeModal();confirmAction({message:`Create a local demo backup for ${game.name}?`,onConfirm:()=>runProgress({title:'Creating Backup',steps:['Preparing backup...','Collecting save data...','Compressing demo archive...','Verifying backup...'],onComplete:async()=>{await createBackup(game);toast('Backup created successfully','success')}})})}},{label:'Verify Files',variant:'btn-secondary',onClick:()=>{closeModal();runProgress({title:'Verify Game Files',steps:['Scanning game directory...','Comparing demo file manifest...','Checking dependencies...','Verification completed'],onComplete:async()=>{await simulateFix(game,'File Verification');toast('File verification completed','success')}})}}]});}
}
const detail=(a,b)=>`<div><span>${a}</span><strong>${b}</strong></div>`;
